version: 0.2

env:
  shell: bash
  parameter-store:
    GIT_USER: "/CodeBuild/Git_USER"
    GIT_PASS: "/CodeBuild/Git_PASS"

phases:
  install:
    commands:
      - echo Executing install phase

      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_REPO_URL
      - org_name=$(echo $CODEBUILD_SOURCE_REPO_URL | awk '{split($0,org,"/"); print org[4]}')
      - echo $org_name
      - echo $CODEBUILD_SOURCE_VERSION

      - echo $CODEBUILD_WEBHOOK_MERGE_COMMIT
      - echo $CODEBUILD_WEBHOOK_PREV_COMMIT
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID
      - echo $CODEBUILD_WEBHOOK_EVENT
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo $CODEBUILD_WEBHOOK_BASE_REF

      # Codebuild only runs on PUSH events if HEAD_REF
      # is refs/heads/develop (merge to develop). In this
      # case CODEBUILD_GIT_BRANCH="develop"

      - if [ "$CODEBUILD_WEBHOOK_EVENT" = "PUSH" ];
        then export CODEBUILD_GIT_BRANCH="develop";
        echo "Merging to develop";
        else export CODEBUILD_GIT_BRANCH=${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/};
        fi

      # Determine the git base branch. This is the branch we are merging into.
      # It can be develop or another branch. It will be used as a fall back branch in clone.sh
      - export GIT_BASE_BRANCH=${CODEBUILD_WEBHOOK_BASE_REF#refs/heads/}

      - echo "GIT_BASE_BRANCH=${GIT_BASE_BRANCH}"
      - echo "CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH}"
      - echo "CODEBUILD_SOURCE_VERSION=${CODEBUILD_SOURCE_VERSION}"

      # read cdash url from s3
      - wget https://ci-test-cdash-url.s3.amazonaws.com/cdash_url.txt
      - CDASH_URL=$(cat cdash_url.txt)

  pre_build:
    commands:
      - echo Executing pre_build phase
      - git lfs install # creates .gitconfig
      - mkdir -p /jcsda/vader-bundle

      # Upload branch name and commit sha as CodeBuild artifact to S3
      - mkdir -p /jcsda/artifacts
      - echo ${CODEBUILD_GIT_BRANCH} > /jcsda/artifacts/branch_name.txt
      - echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} > /jcsda/artifacts/commit_sha.txt

      - cd CI

      #  Setting git credentials
      - sed -i '/ssh/d' ~/.gitconfig
      - sed '/instead/d' ~/.gitconfig
      - git config --global credential.helper store
      - touch ~/.git-credentials
      - chmod 0700 ~/.git-credentials
      - echo "https://${GIT_USER}:${GIT_PASS}@github.com" >~/.git-credentials

      # oops
      - ./clone.sh jcsda-internal/oops $CODEBUILD_GIT_BRANCH  /jcsda/vader-bundle oops ${GIT_BASE_BRANCH} develop

      # gsw
      - ./clone.sh jcsda-internal/GSW-Fortran $CODEBUILD_GIT_BRANCH  /jcsda/vader-bundle gsw ${GIT_BASE_BRANCH} develop

      # vader
      - ./clone.sh jcsda-internal/vader $CODEBUILD_GIT_BRANCH  /jcsda/vader-bundle vader ${GIT_BASE_BRANCH} develop

      # move CMakeLists.txt
      - cp CMakeLists.txt /jcsda/vader-bundle
      - cp -r cmake /jcsda/vader-bundle/
      # cdash upload setup
      - cp /jcsda/vader-bundle/cmake/CTestConfig.cmake /jcsda/vader-bundle/
      - sed -i "s@CDASH_URL@$CDASH_URL@g" /jcsda/vader-bundle/CTestConfig.cmake

      - cd /jcsda/vader-bundle

      - chmod -R 777 /jcsda/vader-bundle

  build:
    on-failure: CONTINUE
    commands:
      - echo Executing build phase
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - export BUILD_STATUS="0"
      - echo $BUILD_STATUS

     # configure and build
      - su - nonroot -c "cd /home/nonroot
        && echo $CC
        && echo $CXX
        && echo $FC
        && CC=mpicc CXX=mpicxx FC=mpifort ecbuild -Wno-dev -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCDASH_OVERRIDE_SITE=CodeBuild -DCDASH_OVERRIDE_SYSTEM_NAME=GNUContainer -DCDASH_OVERRIDE_GIT_BRANCH=$CODEBUILD_GIT_BRANCH -DCTEST_UPDATE_VERSION_ONLY=FALSE -DENABLE_GPROF=ON /jcsda/vader-bundle/"

      - su - nonroot -c "cd /home/nonroot/vader
        && echo $CC
        && echo $CXX
        && echo $FC
        && cp ../DartConfiguration.tcl .
        && sed -i 's/vader-bundle/vader-bundle\/vader/' DartConfiguration.tcl
        && sed -i 's/nonroot/nonroot\/vader/' DartConfiguration.tcl
        && cat DartConfiguration.tcl
        && make -j4"

      - if [ "$CODEBUILD_BUILD_SUCCEEDING" = "1" ];
        then export BUILD_STATUS="1";
        echo "Build passed";
        fi
      - echo $BUILD_STATUS

      # run ctest
      - su - nonroot -c "CC=mpicc CXX=mpicxx FC=mpifort
        && cd /home/nonroot/vader
        && ctest -C RelWithDebInfo -D ExperimentalTest"

    finally:
      # upload ctest report to CDASH
      - su - nonroot -c "CC=mpicc CXX=mpicxx FC=mpifort
        && cd /home/nonroot/vader
        && ctest -C RelWithDebInfo -D ExperimentalSubmit -M Continuous -- --track Continuous --group Continuous"

  post_build:
    commands:
      - echo Executing post_build phase
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - echo $BUILD_STATUS

      # upload find cdash url and upload it as CodeBuild artifact to S3
      - if [ "$BUILD_STATUS" = "1" ];
        then echo "Build & tests passed, find cdash url";
        url=$(bash /jcsda/vader-bundle/vader/CI/cdash-url.sh /home/nonroot/vader/Testing $CDASH_URL);
        echo $url;
        echo ${url} > /jcsda/artifacts/cdash-url.txt;
        cat /jcsda/artifacts/cdash-url.txt;
        else echo "Build failed";
        fi

      - cd /home/nonroot/vader
      - bash /jcsda/vader-bundle/vader/CI/codecov_script.sh

artifacts:
  files:
    - '/jcsda/artifacts/*'
  name: vader-gnu-url
